# This is a sample configuration file
services:
  otc:
    urls:
      - "https://www.open-telekom-cloud.com"
  console:
    urls:
      - "https://console.otc.t-systems.com"
      - "https://auth.otc.t-systems.com/authui/login.action#/login"
  helpcenter:
    urls:
      - "https://docs.otc.t-systems.com"
  architecturecenter:
    urls:
      - "https://arch.otc-service.com"
  community:
    urls:
      - "https://community.open-telekom-cloud.com/community?id=community_home"
  obs:
    urls:
      - "https://sd2-eu-nl-globalmon.obs.eu-nl.otc.t-systems.com/sd2-test-object.txt"
      - "https://sd2-eu-nl-globalmon.obs.eu-nl.otc.t-systems.com"
  enterprise_dashboard_v2:
    urls:
      - "https://api-enterprise-dashboard.otc-service.com/v2/health/"
