# This is a sample configuration file
services:
  otc:
    urls:
      - "https://www.open-telekom-cloud.com"
  console:
    urls:
      - "https://console.sc.otc.t-systems.com"
      - "https://auth.sc.otc.t-systems.com/authui/login.action#/login"
  helpcenter-swiss:
    urls:
      - "https://docs.sc.otc.t-systems.com"
  community:
    urls:
      - "https://community.open-telekom-cloud.com/community?id=community_home"
  obs:
    urls:
      - "https://sd2-eu-ch2-globalmon.obs.eu-ch2.sc.otc.t-systems.com/sd2-eu-ch2-test-object.txt"
      - "https://sd2-eu-ch2-globalmon.obs.eu-ch2.sc.otc.t-systems.com"

